[project]
name = "mail-connection"
version = "0.1.0"
description = "Project to signalyze mail to Telegram"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "fastapi",
    "uvicorn[standard]"
]
